"""Render the red-team scorecard to markdown."""

from datetime import UTC, datetime
from pathlib import Path

from evidencegene.redteam.harness import AttemptResult


def write_report(results: list[AttemptResult], path: Path) -> None:
    defended = sum(1 for r in results if r.defended)
    lines = [
        "# Red-team Report — Injection Harness (GTG-1002 mirror)",
        "",
        "> Autonomously attacks the defender and proves the architecture neutralizes "
        "each attempt. Every attack targets a trust boundary; deterministic, no LLM. "
        "Generated by `egc-court redteam`.",
        "",
        f"Generated: {datetime.now(UTC).isoformat()}",
        "",
        f"## Scorecard: {defended}/{len(results)} defended",
        "",
    ]
    for r in results:
        mark = "DEFENDED" if r.defended else "BYPASSED"
        lines.append(f"- **[{mark}] {r.payload_id} — {r.name}**")
        lines.append(f"  - ATLAS: `{r.atlas_id}`")
        lines.append(f"  - Category: `{r.category}`")
        lines.append(f"  - Outcome: {r.detail}")
    lines.append("")
    lines.append(
        "Each attempt is also recorded as a `redteam_attempt` event in the audit "
        "chain, so this scorecard is itself tamper-evident."
    )
    lines.append("")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")
